server:
  port: 8073

spring:
#  profiles:
#    active: dev
  application:
    name: sample

logging:
  file: ${spring.application.name}
  path: logs
  level:
     com:
       bqr:
         framework: debug









