swagger:  #惠农swagger配置
   enable: true  # 是否开启swagger，建议生产关闭，默认true
   basePackage: com.bqr.framework.sample.web  #swagger扫描的api包，不能为空
   title: 惠农行情接入API列表  # 标题
   description: 惠农行情接入API列表 #描述
   groupName: 测试组



spring:
  datasource:
    url: jdbc:mysql://rm-uf69j55wv3m56puj5o.mysql.rds.aliyuncs.com:3306/b2b_market
    username: root
    password: XiangYR-816
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: test
  application:
    name: bqr-framework-starter-sample



mybatis:
    type-aliases-package: com.bqr.framework.sample.entity
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false

mapper:
    mappers: com.bqr.framework.mybatis.mapper.FrameworkBaseMapper
    not-empty: false
    identity: MYSQL
    before: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  file: ${spring.application.name}
  path: logs
  level:
     com:
       bqr:
         framework: debug