mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    config-location:  classpath:mybatis-config.xml

mapper:
    mappers: com.bqr.framework.mybatis.mapper.FrameworkBaseMapper
    not-empty: false
    identity: MYSQL
    before: true

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql